### ISSUE TITLE
Congrats! 

### ISSUE THREAD

**Issue by Kommand1** [ludwig-v/arduino-psa-diag#1]
Really good work!

Connection to arduino works. 

Connection to a ecu works. 

See what is given out by software works. 

But, what does not work is, sending the same commands to a unit like that what was given out from diagbox. 

Could you please do a explanation for it. 

Something like a tutorial?

V/R

Greetings from Austria

**Comment by ludwig-v** [comment]
To help you it would be better if you write what you are trying to send

**Comment by Kommand1** [comment]
Wow, verry fast answer.

Thanks. 

I want to code generally on my car. 

See what I can do there. 

Like combined cluster coding or bsi coding and so on. 

I see your hours/days/months of work.

But to put it together all it seems a little but hard to understand without a tutorial. 

Is there a donate button anywhere?

**Comment by ludwig-v** [comment]
Everything is RAW, I guess you want to know how you can use Diagbox live dump to make something useful, the thing is that it is not easy with or without a tutorial, you must change a parameter to multiple values using Diagbox and see what byte changed to identify its zone and position (could also be a single bit inside a byte), each ECU needs its own conversion table. It is a huge amount of work needed to make a single ECU and the BSI has many settings (but at least almost every setting on the BSI is a 1 byte zone)
You can also change byte values one by one and identify visual changes but it would be partial and it won't work for all ECUs since many of them don't have any visual interface

**Comment by Kommand1** [comment]
I can see what your diagbox gives out with your arduino sketch.

The dumpode enabling worked. 

Yes, if you could explain it for one example how to change a parameter to multiple values using Diagbox and see what byte changed to identify its zone and position, it would be maken it easier.

Of cause it as a lot of work, I see your point. 

But it is definitively interesting and could make fun.

**Comment by FelixdeVuist** [comment]
Good morning Vlud,

For me it is the same like @Kommand1 wrote.

Another thing is that I understand and see the id's for ecu wich are communicating. 

What I can't see are things like "E4D8" for the ecu and where this data is from.

A little how to would be great. 

Thanks for reply.

**Comment by ludwig-v** [comment]
Because it is not something you can see, it is part of the [seed/key algorithm](https://www.semanticscholar.org/paper/Evaluation-of-Vehicle-Diagnostics-Security-%E2%80%93-of-a-Ring-rensen/81027aa2d31b59f7d16ef815afa6986e4e8bc542) (Figure 4) and it is part of another [Github repo](https://github.com/ludwig-v/psa-seedkey-algorithm) (Explained a bit) - E4D8 is an **intermediate key** to use the same algorithm for all ECU, not the final key -

**Comment by ludwig-v** [comment]
`if you could explain it for one example how to change a parameter to multiple values using Diagbox`

You just have to telecode your ECU using the standard procedure to all values possible (it takes a long time since Diagbox can be slow as hell), the hard part is to see changes in the dump because Diagbox reads & writes multiple times, this work could be made a little easier with an additional soft I didn't make.

**Comment by FelixdeVuist** [comment]
Thank you, could you explain how to do?

By the way I opened my crashed nac yesterday. 

I found some connectors inside the nac wich are not connected. 

I will do photos to your repository.

**Comment by ludwig-v** [comment]
How to do what ? Everything is explained inside the repo ... even @morcibacsi added the bruteforce to determine possible (intermediate) keys from a list a valid seed / key pairs dumped from Diagbox. Anyway, this subject is **NOT** part of this repo.

**Comment by ludwig-v** [comment]
How to do what ? Everything is explained inside the repo ... even @morcibacsi added the bruteforce to determine possible (intermediate) keys from a list of valid seed / key pairs dumped from Diagbox. Anyway, this subject is **NOT** part of this repo.

**Comment by FelixdeVuist** [comment]
I will note down what I try to do and upload it here with all what the arduino shows me.

**Comment by FelixdeVuist** [comment]
Example:

Trying to read and clear fault of bsi:

When entering 3101DF01

Normally the answer should be 7101DF0102
(that's a output of diag with your sketch) 

When I enter manually, I get 7F3122 as answer. 

So what am I doing wrong? 

Thanks for answer.

**Comment by Kommand1** [comment]
Good Day,

This what I took. 

23:26:07.683 -> Dump mode
23:26:14.464 -> 77B:1003
23:26:14.464 -> 67B:500300C80014
23:26:14.510 -> 77B:22F080
23:26:14.557 -> 652:62F08096777660770024967776607707050603000104267699
23:26:41.071 -> 77B:190209
23:26:41.118 -> 652:590209DF2B8709DF000009
23:26:49.555 -> 77B:14FFFFFF
23:26:49.602 -> 67B:54
23:26:50.774 -> 77B:190209
23:26:50.821 -> 67B:590209

When I try to do it via terminal it does not work.
I Am in the Ecu, that is working. 
When I am at the point to enter 190209,
It allways sends me one message back. Allways the same. 
Doesn't matter what I Type in.

Any clue where the mistake is?

Thanks for your support.

**Comment by ludwig-v** [comment]
@Kommand1 : 14FFFFFF is clearing the faults, 190209 is displaying the current faults, so since there is no more faults (removed by Diagbox before) it is normal to get an empty message after

@FelixdeVuist : 3101DF01 is not the first command issued to clear faults of the BSI, 3101DF0A05 must be sent right before issuing that command else you get an error
